name: movieticketbookingapp

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  loading_overlay: ^0.3.0
  location: ^6.0.2
  google_sign_in: ^6.2.1
  razorpay_flutter: ^1.3.7
  cached_network_image: ^3.4.0
  dotted_border: ^2.1.0
  geocoding: ^3.0.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  google_maps_flutter: ^2.6.1
  cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
    - assets/actors/
    - assets/movies/
    - assets/events/
    - assets/plays/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
